version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: velib_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  airflow-webserver:
    build: .
    container_name: velib_airflow_webserver
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "p3I1b0d4r3f_7m8qv9H1r4W5z6yQxL2mN3oP0qR1sT4="
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      JCDECAUX_API_KEY: ${JCDECAUX_API_KEY}
      TZ: Europe/Paris
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./script:/opt/airflow/script
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username admin
        --password admin
        --firstname Thierno
        --lastname Bah
        --role Admin
        --email thierno.ibrahima.bah@gmail.com || true &&
      airflow webserver
      "

  airflow-scheduler:
    build: .
    container_name: velib_airflow_scheduler
    restart: unless-stopped
    depends_on:
      airflow-webserver:
        condition: service_started
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: "p3I1b0d4r3f_7m8qv9H1r4W5z6yQxL2mN3oP0qR1sT4="
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      JCDECAUX_API_KEY: ${JCDECAUX_API_KEY}
      TZ: Europe/Paris
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./script:/opt/airflow/script
    command: >
      bash -c "
      airflow db init &&
      airflow scheduler
      "

  velib_app:
    build: .
    container_name: velib_app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      TZ: Europe/Paris
    ports:
      - "8501:8501"
    command: >
      bash -c "streamlit run script/app_streamlit.py
      --server.port=8501
      --server.address=0.0.0.0"

volumes:
  mongo_data:
  postgres_data:
